#!/bin/sh
# This script is designed to work with Archlinux

# Detect if an Nvidia GPU is installed
GPU=`lshw -class video | grep "vendor" | cut -d ":" -f 2 | cut -d " " -f 2`

# Detect currently running kernel's tag
KERNEL_TAG=`uname -r | cut -d "-" -f 4`

# Coomandline argument passed
NVIDIA_TOGGLE="$1"

# Check if user is root
if [[ "$USER" == "root" ]]; then

	# Check if there is only one argument
	if [[ "$#" == "1" ]]; then

		# Check if nvidia hardware is present
		if [[ "${GPU}" == "NVIDIA" ]]; then

			# Check which driver the user wants to install
			if [[ "${NVIDIA_TOGGLE}" == "official" ]]; then

				# Install all the needed packages for the proprietary nvidia driver
				pacman -Syy --noconfirm lib32-nvidia-utils lib32-opencl-nvidia libva-nvidia-driver libvdpau-va-gl nvidia-open-dkms nvidia-prime nvidia-settings nvidia-utils nvtop opencl-nvidia vdpauinfo
				pacman -Rsc --noconfirm lib32-vulkan-nouveau vulkan-nouveau

				# Enable all Nvidia driver GPU services
				systemctl enable nvidia-hibernate.service
				systemctl enable nvidia-persistenced.service
				systemctl enable nvidia-powerd.service
				systemctl enable nvidia-resume.service
				systemctl enable nvidia-suspend.service
				systemctl enable nvidia-suspend-then-hibernate.service

				# Blacklist the nouveau GPU driver
				echo "install nouveau /bin/false" /etc/modprobe.d/blacklist-nouveau.conf

				# Rebuild kernel images
				if [[ "$KERNEL_TAG" != "arch" ]]; then
					mkinitcpio -p linux-${KERNEL_TAG}
				else
					mkinitcpio -p linux
				fi

				# Reboot System
				slepp 5
				systemctl reboot

			elif [[ "${NVIDIA_TOGGLE}" == "foss" ]]; then

				# Disable all Nvidia driver GPU services
				systemctl disable nvidia-hibernate.service
				systemctl disable nvidia-persistenced.service
				systemctl disable nvidia-powerd.service
				systemctl disable nvidia-resume.service
				systemctl disable nvidia-suspend.service
				systemctl disable nvidia-suspend-then-hibernate.service

				# Install only the needed packages for the foss nouveau driver
				pacman -Syy --noconfirm lib32-vulkan-nouveau vulkan-nouveau
				pacman -Rsc --noconfirm lib32-nvidia-utils lib32-opencl-nvidia libva-nvidia-driver libvdpau-va-gl nvidia-open-dkms nvidia-prime nvidia-settings nvidia-utils nvtop opencl-nvidia vdpauinfo

				# Remove nouveau blacklist
				rm /etc/modprobe.d/blacklist-nouveau.conf

				# Rebuild kernel images
				if [[ "$KERNEL_TAG" != "arch" ]]; then
					mkinitcpio -p linux-${KERNEL_TAG}
				else
					mkinitcpio -p linux
				fi

				# Reboot System
				slepp 5
				systemctl reboot

			else

				# Help Message
				echo "Usage: ./nvidia_driver_toggle: type official or foss"

			fi

		else

			# Error message
			echo "Nvidia hardware not detected"

		fi

	else

		# Error Message
		echo "Please type in 1 argument"

	fi

else

	# Error Message
	echo "You must run this script as the root user"

fi
